#!/usr/bin/env python3
import os
import sys
import subprocess
from colorama import Fore, Style, init

init(autoreset=True)

def install_framework():
    print(f"{Fore.CYAN}╔══════════════════════════════════════════════════╗")
    print(f"║         PENTEST-WEB FRAMEWORK INSTALLER          ║")
    print(f"║          32-in-1 Vulnerability Scanner           ║")
    print(f"╚══════════════════════════════════════════════════╝{Style.RESET_ALL}")
    
    
    print(f"{Fore.YELLOW}[+] Creating directory structure...{Style.RESET_ALL}")
    
    directories = [
        "modules",
        "payloads",
        "results",
        "reports",
        "logs"
    ]
    
    for directory in directories:
        os.makedirs(directory, exist_ok=True)
        print(f"  {Fore.GREEN}✓{Style.RESET_ALL} {directory}/")
    
    
    print(f"{Fore.YELLOW}[+] Installing dependencies...{Style.RESET_ALL}")
    
    dependencies = [
        "requests",
        "colorama",
        "beautifulsoup4",
        "lxml",
        "dnspython",
        "urllib3"
    ]
    
    for dep in dependencies:
        try:
            subprocess.check_call([sys.executable, "-m", "pip", "install", dep])
            print(f"  {Fore.GREEN}✓{Style.RESET_ALL} {dep}")
        except:
            print(f"  {Fore.RED}✗{Style.RESET_ALL} Failed to install {dep}")
    
    
    print(f"{Fore.YELLOW}[+] Creating payload files...{Style.RESET_ALL}")
    create_payloads()
    
    
    print(f"{Fore.YELLOW}[+] Creating scanner modules...{Style.RESET_ALL}")
    create_basic_modules()
    
    
    if not os.path.exists("main.py"):
        with open("main.py", "w") as f:
            f.write('''#!/usr/bin/env python3
print("Pentest-Web Framework")
print("Run: python3 installer.py to setup")
''')
    
    print(f"\n{Fore.GREEN}[✓] Installation complete!{Style.RESET_ALL}")
    print(f"{Fore.CYAN}[→] Run: python3 main.py{Style.RESET_ALL}")
    print(f"{Fore.CYAN}[→] 32 Scanner modules ready{Style.RESET_ALL}")

def create_payloads():
    """Create all payload files"""
    payload_files = [
        "sqli.txt", "xss.txt", "lfi.txt", "rfi.txt",
        "command_injection.txt", "rce.txt", "xxe.txt",
        "ssrf.txt", "crlf.txt", "open_redirect.txt",
        "ssti.txt", "idor.txt", "csrf.txt", 
        "file_upload.txt", "cors.txt", "jwt.txt",
        "traversal.txt"
    ]
    
    for filename in payload_files:
        with open(f"payloads/{filename}", "w") as f:
            f.write(f"# {filename.replace('.txt', '').upper()} Payloads\n")
            f.write("# Generated by Pentest-Web\n\n")
            f.write("payload1\npayload2\npayload3\n")
        print(f"  {Fore.GREEN}✓{Style.RESET_ALL} payloads/{filename}")

def create_basic_modules():
    """Create basic module templates"""
    modules = [
        "sql_injection.py", "xss_scanner.py", "command_injection.py",
        "rce_scanner.py", "lfi_scanner.py", "rfi_scanner.py",
        "xxe_scanner.py", "ssrf_scanner.py", "crlf_injection.py",
        "open_redirect.py", "ssti_scanner.py", "idor_scanner.py",
        "csrf_tester.py", "file_upload.py", "cors_scanner.py",
        "subdomain_takeover.py", "dns_zone.py", "api_scanner.py",
        "jwt_scanner.py", "http_smuggling.py", "clickjacking.py",
        "cookie_scanner.py", "security_headers.py", "info_disclosure.py",
        "directory_traversal.py", "hpp_scanner.py", "business_logic.py",
        "auth_bypass.py", "session_fixation.py", "cache_poisoning.py",
        "oauth_scanner.py", "graphql_scanner.py"
    ]
    
    for module in modules:
        with open(f"modules/{module}", "w") as f:
            f.write(f'''#!/usr/bin/env python3
"""
{module.replace('.py', '').replace('_', ' ').title()} Scanner
Pentest-Web Framework
"""

def main():
    print("{module.replace('.py', '').replace('_', ' ').title()} Scanner")
    print("Module ready for implementation")

if __name__ == "__main__":
    main()
''')
        print(f"  {Fore.GREEN}✓{Style.RESET_ALL} modules/{module}")

if __name__ == "__main__":
    install_framework()
